/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainGame;

/**
 *
 * @author Akshat Sharma
 */
public class main_game_screen extends javax.swing.JFrame {

    /**
     * Creates new form main_game_screen
     */
    public main_game_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        colonistname = new javax.swing.JLabel();
        colonist = new javax.swing.JLabel();
        scannerallname = new javax.swing.JLabel();
        Atmospherename = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        gravname = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        tempname = new javax.swing.JLabel();
        atmos = new javax.swing.JLabel();
        watername = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        resoname = new javax.swing.JLabel();
        grav = new javax.swing.JLabel();
        sysname = new javax.swing.JLabel();
        landname = new javax.swing.JLabel();
        land = new javax.swing.JLabel();
        consname = new javax.swing.JLabel();
        cons = new javax.swing.JLabel();
        spname1 = new javax.swing.JLabel();
        surfprob = new javax.swing.JLabel();
        spname2 = new javax.swing.JLabel();
        dataname = new javax.swing.JLabel();
        sciname = new javax.swing.JLabel();
        sci = new javax.swing.JLabel();
        culturalname = new javax.swing.JLabel();
        cul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        line01 = new javax.swing.JLabel();
        line02 = new javax.swing.JLabel();
        line03 = new javax.swing.JLabel();
        line04 = new javax.swing.JLabel();
        line05 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        line11 = new javax.swing.JLabel();
        line12 = new javax.swing.JLabel();
        line13 = new javax.swing.JLabel();
        line14 = new javax.swing.JLabel();
        line15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        line21 = new javax.swing.JLabel();
        line22 = new javax.swing.JLabel();
        line23 = new javax.swing.JLabel();
        line24 = new javax.swing.JLabel();
        line25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        line31 = new javax.swing.JLabel();
        line32 = new javax.swing.JLabel();
        line33 = new javax.swing.JLabel();
        line34 = new javax.swing.JLabel();
        line35 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        line41 = new javax.swing.JLabel();
        line42 = new javax.swing.JLabel();
        line43 = new javax.swing.JLabel();
        line44 = new javax.swing.JLabel();
        line45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        colonistname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        colonistname.setForeground(new java.awt.Color(255, 255, 255));
        colonistname.setText("Colonists");

        colonist.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        colonist.setForeground(new java.awt.Color(102, 204, 0));
        colonist.setText("1000");

        scannerallname.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        scannerallname.setForeground(new java.awt.Color(255, 255, 255));
        scannerallname.setText("Scanners");

        Atmospherename.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        Atmospherename.setForeground(new java.awt.Color(255, 255, 255));
        Atmospherename.setText("Atmosphere");

        res.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        res.setForeground(new java.awt.Color(102, 204, 0));
        res.setText("100%");

        gravname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        gravname.setForeground(new java.awt.Color(255, 255, 255));
        gravname.setText("Gravity");

        temp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        temp.setForeground(new java.awt.Color(102, 204, 0));
        temp.setText("100%");

        tempname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        tempname.setForeground(new java.awt.Color(255, 255, 255));
        tempname.setText("Temperature");

        atmos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        atmos.setForeground(new java.awt.Color(102, 204, 0));
        atmos.setText("100%");

        watername.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        watername.setForeground(new java.awt.Color(255, 255, 255));
        watername.setText("Water");

        water.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        water.setForeground(new java.awt.Color(102, 204, 0));
        water.setText("100%");

        resoname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        resoname.setForeground(new java.awt.Color(255, 255, 255));
        resoname.setText("Resourses");

        grav.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        grav.setForeground(new java.awt.Color(102, 204, 0));
        grav.setText("100%");

        sysname.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        sysname.setForeground(new java.awt.Color(255, 255, 255));
        sysname.setText("Systems");

        landname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        landname.setForeground(new java.awt.Color(255, 255, 255));
        landname.setText("Landing");

        land.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        land.setForeground(new java.awt.Color(102, 204, 0));
        land.setText("100%");

        consname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        consname.setForeground(new java.awt.Color(255, 255, 255));
        consname.setText("Construction");

        cons.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cons.setForeground(new java.awt.Color(102, 204, 0));
        cons.setText("100%");

        spname1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        spname1.setForeground(new java.awt.Color(255, 255, 255));
        spname1.setText("Surface");

        surfprob.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        surfprob.setForeground(new java.awt.Color(255, 255, 255));
        surfprob.setText("10");

        spname2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        spname2.setForeground(new java.awt.Color(255, 255, 255));
        spname2.setText("Probes");

        dataname.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        dataname.setForeground(new java.awt.Color(255, 255, 255));
        dataname.setText("Databases");

        sciname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        sciname.setForeground(new java.awt.Color(255, 255, 255));
        sciname.setText("Scientific");

        sci.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sci.setForeground(new java.awt.Color(102, 204, 0));
        sci.setText("100%");

        culturalname.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        culturalname.setForeground(new java.awt.Color(255, 255, 255));
        culturalname.setText("Cultural");

        cul.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cul.setForeground(new java.awt.Color(102, 204, 0));
        cul.setText("100%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scannerallname)
                    .addComponent(Atmospherename)
                    .addComponent(sysname)
                    .addComponent(dataname)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gravname)
                            .addComponent(tempname)
                            .addComponent(watername)
                            .addComponent(resoname)
                            .addComponent(landname)
                            .addComponent(consname)
                            .addComponent(spname1)
                            .addComponent(spname2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sciname)
                            .addComponent(culturalname)
                            .addComponent(colonistname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colonist, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cul)
                            .addComponent(sci)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(land, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(water, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(grav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atmos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(surfprob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colonistname)
                    .addComponent(colonist))
                .addGap(24, 24, 24)
                .addComponent(scannerallname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atmospherename)
                    .addComponent(atmos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gravname)
                    .addComponent(grav))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempname)
                    .addComponent(temp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(watername)
                    .addComponent(water))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resoname)
                    .addComponent(res))
                .addGap(18, 18, 18)
                .addComponent(sysname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landname)
                    .addComponent(land))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consname)
                    .addComponent(cons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spname2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(surfprob, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(dataname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sciname)
                    .addComponent(sci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culturalname)
                    .addComponent(cul))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        line01.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line01.setForeground(new java.awt.Color(255, 255, 255));

        line02.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line02.setForeground(new java.awt.Color(255, 255, 255));

        line03.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line03.setForeground(new java.awt.Color(255, 255, 255));

        line04.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line04.setForeground(new java.awt.Color(255, 255, 255));

        line05.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line05.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line05)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        line11.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line11.setForeground(new java.awt.Color(255, 255, 255));

        line12.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line12.setForeground(new java.awt.Color(255, 255, 255));

        line13.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line13.setForeground(new java.awt.Color(255, 255, 255));

        line14.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line14.setForeground(new java.awt.Color(255, 255, 255));

        line15.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line15.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        line21.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line21.setForeground(new java.awt.Color(255, 255, 255));

        line22.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line22.setForeground(new java.awt.Color(255, 255, 255));

        line23.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line23.setForeground(new java.awt.Color(255, 255, 255));

        line24.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line24.setForeground(new java.awt.Color(255, 255, 255));

        line25.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line25.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        line31.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line31.setForeground(new java.awt.Color(255, 255, 255));

        line32.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line32.setForeground(new java.awt.Color(255, 255, 255));

        line33.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line33.setForeground(new java.awt.Color(255, 255, 255));

        line34.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line34.setForeground(new java.awt.Color(255, 255, 255));

        line35.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line35.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line32, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
                    .addComponent(line33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        line41.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line41.setForeground(new java.awt.Color(255, 255, 255));

        line42.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line42.setForeground(new java.awt.Color(255, 255, 255));

        line43.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line43.setForeground(new java.awt.Color(255, 255, 255));

        line44.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line44.setForeground(new java.awt.Color(255, 255, 255));

        line45.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        line45.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line42, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                    .addComponent(line43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 266, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_game_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atmospherename;
    private javax.swing.JLabel atmos;
    private javax.swing.JLabel colonist;
    private javax.swing.JLabel colonistname;
    private javax.swing.JLabel cons;
    private javax.swing.JLabel consname;
    private javax.swing.JLabel cul;
    private javax.swing.JLabel culturalname;
    private javax.swing.JLabel dataname;
    private javax.swing.JLabel grav;
    private javax.swing.JLabel gravname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel land;
    private javax.swing.JLabel landname;
    private javax.swing.JLabel line01;
    private javax.swing.JLabel line02;
    private javax.swing.JLabel line03;
    private javax.swing.JLabel line04;
    private javax.swing.JLabel line05;
    private javax.swing.JLabel line11;
    private javax.swing.JLabel line12;
    private javax.swing.JLabel line13;
    private javax.swing.JLabel line14;
    private javax.swing.JLabel line15;
    private javax.swing.JLabel line21;
    private javax.swing.JLabel line22;
    private javax.swing.JLabel line23;
    private javax.swing.JLabel line24;
    private javax.swing.JLabel line25;
    private javax.swing.JLabel line31;
    private javax.swing.JLabel line32;
    private javax.swing.JLabel line33;
    private javax.swing.JLabel line34;
    private javax.swing.JLabel line35;
    private javax.swing.JLabel line41;
    private javax.swing.JLabel line42;
    private javax.swing.JLabel line43;
    private javax.swing.JLabel line44;
    private javax.swing.JLabel line45;
    private javax.swing.JLabel res;
    private javax.swing.JLabel resoname;
    private javax.swing.JLabel scannerallname;
    private javax.swing.JLabel sci;
    private javax.swing.JLabel sciname;
    private javax.swing.JLabel spname1;
    private javax.swing.JLabel spname2;
    private javax.swing.JLabel surfprob;
    private javax.swing.JLabel sysname;
    private javax.swing.JLabel temp;
    private javax.swing.JLabel tempname;
    private javax.swing.JLabel water;
    private javax.swing.JLabel watername;
    // End of variables declaration//GEN-END:variables
}
